FROM node:18-slim

WORKDIR /app

COPY package*.json .

RUN npm install --only=production

COPY important_info.txt .

COPY important_info2.txt /


USER node

COPY --chown=node:node file.js .

CMD node file.js