FROM python:3.11-slim

WORKDIR /usr/app

COPY requirements.txt ./

RUN pip install -r requirements.txt \
	&& apt-get update && apt-get install --no-install-recommends -y httpie \
	&& rm -rf /var/lib/apt/lists/* \
	&& http http://example.com -o file.html \
	&& useradd python
USER python

COPY --chown=python:python . .

CMD python3 main.py